### ISSUE TITLE
Remove "(formerly DOM Level 3 Events)" from the title?

### ISSUE THREAD

**Issue by AFBarstow** [w3c/uievents#1]
In a week or so, the second WD of uievents will be published and as such, perhaps "(formerly DOM Level 3 Events)" should now be removed from the title.

**Comment by travisleithead** [comment]
I'd keep it for a bit. There's a long history of folks searching for that name, and I want to keep SEO optimized for a bit longer (perhaps by next TPAC we can remove it).

**Comment by travisleithead** [comment]
OK it was time to drop it.
