### ISSUE TITLE
Can't suppress the default action of non-primary button clicks

### ISSUE THREAD

**Issue by RByers** [w3c/uievents#107]
Long ago UI Events was changed to say that `click` [fires only for the primary mouse button](https://w3c.github.io/uievents/#event-type-click).  In trying to make blink conform to this, we've found there are some (rare) legitimate use cases where developers need to detect and possibly even cancel the default action associated with a middle button mouse click.

For example, in a tabbed UI clicking the middle button on a tab is expected to close it (not navigate to any link that happens to also be there).  Or in some scenarios (eg. GMail) an application can do a better job of opening a link in a new window itself via JavaScript rather than leaving the navigation up to the browser.

To address this need [@NavidZ has proposed](https://discourse.wicg.io/t/new-event-for-non-primary-button-click/1527) a new [`auxclick` event](https://wicg.github.io/auxclick/).  The basic premise is that ideally `click` is used just for the common action (since much usage of it won't ever think to check for things like unusual buttons) and a rarely used additional event is reserved for the special cases.

According to blink's "[incubation first standards policy](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/PJ_E04kcFb8/ZXJXLJYYAAAJ)" we're [planning on shipping this event](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/R8OehqGJzt0) based on [discussion in the WICG](https://discourse.wicg.io/t/new-event-for-non-primary-button-click/1527).  For now please file any issues [here](https://github.com/NavidZ/auxclick/issues).

We don't yet know if this will succeed.  In particular, it's a breaking change of long-standing behavior for Chrome not to fire `click` for the middle button.  This change is currently slated to hit Chrome 55 stable sometime around early December, so we should know for sure if it will stick by the end of the year. If all goes well with this, and other vendors become interested in implementing `auxclick` too, then we hope that the WPWG will consider adopting `auxclick`into UI Events.

**Comment by RByers** [comment]
[This](https://developer.mozilla.org/en-US/docs/Web/Events/auxclick) has been shipping for a long time in Chrome and is now [shipping in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1304044).  Perhaps it's time to consider graduating it from WICG to UI Events?
@smaug---- @garykac WDYT?

**Comment by garykac** [comment]
sgtm. Esp. if it's shipping in 2 browsers.  Microsoft (travis) also gave an
lgtm to the idea during incubation. I didn't see any comments from Apple,
but I assume they would have commented if they had a strong opinion.

**Comment by smaug----** [comment]
Yeah, I think we need to get the event to some real spec.

**Comment by lpd-au** [comment]
The `auxclick` event link in the issue description appears to be dead.

**Comment by anonym24** [comment]
Tell guys from Microsoft to add this auxclick event, in that browser nothing works at all for middle click. Also can I hear why W3C decided to remove "_events_" and "_prevent default functions_" for middle mouse click? Why they didn't remove for right and left click as well?
