### ISSUE TITLE
Mark up IDL attributes properly

### ISSUE THREAD

**Issue by domenic** [w3c/uievents#110]
Right now there is no connected between the definition of e.g. MouseEvent's ctrlKey, and the IDL. This requires some Bikeshed tricks: instead of

``` html
<dt>MouseEvent . ctrlKey</dt>
```

write

``` html
<dt><dfn attribute for="MouseEvent">ctrlKey</dfn></dt>
```

(Also please don't use the InterfaceName.attributeName notation.)

This makes it easier for other specs to link to you, and will avoid the accidental linking to CSSOM that is done for screenX and friends.

**Comment by garykac** [comment]
What's the correct way to tag functions (like `getModifierState(keyArg)`)?

I tried
```
<dl dfn-for="MouseEvent">
  ...
  <dt><dfn function>getModifierState(keyArg)</dfn></dt>
  ...
</dl>
```
But it didn't link to the IDL like the `<dfn attribute>`s did.

**Comment by domenic** [comment]
Based on https://tabatkins.github.io/bikeshed/#dfn-types it's `<dfn method>`
