### ISSUE TITLE
Printable control characters needs refinement

### ISSUE THREAD

**Issue by r12a** [w3c/uievents#121]
https://w3c.github.io/uievents/#keys-guidelines

> If the key generates a printable character, and there exists an appropriate Unicode code point, then the key attribute MUST be a string consisting of the char value of that character.

https://w3c.github.io/uievents/#interface-keyboardevent

> KeyboardEventInit . key ... If the key is not a printable character, then it should be one of the key values defined in [UIEvents-Key]. 

https://w3c.github.io/uievents-key/#key-value-tables
2. Keyboard Event key Value Tables

> If the key represents one of the set of printable control characters which has a Unicode character entry

It would be useful to have a definition of 'printable characters' in the glossary, and to point to that where the term is used in this technical sense.

However, that definition may need some careful wording. For example, I assume that it includes characters such as ZWJ, ZWNJ, RLM, LRM, ZWSP, etc. which are printable in the sense that the key that produces them would result in characters that can be identified, but they are characters that  cannot be detected visually when printed or displayed.

This case is muddied a little by the wording in 
https://w3c.github.io/uievents/#interface-keyboardevent
which says:

> If the value is a control key which has no printed representation, it MUST be one of the key values defined in the key values set, ...

This sentence also, by using 'printed representation' as ordinary text, seems to exclude the above characters.

**Comment by garykac** [comment]
Fixed (see above)
