### ISSUE TITLE
Needs an option to make the <input> element readonly in "Keyboard Event Viewer"

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/uievents#137]
I really love Keyboard Event Viewer: https://w3c.github.io/uievents/tools/key-event-viewer.html

However, I cannot test some special cases with this unfortunately. The cases are, keyboard events on non-editable element. For example, when non-editable element has focus, composition won't be started usually. Therefore, keyboard events for a dead key sequence may be different if focus is in readonly editor.

So, I hope that there is a checkbox to toggle readonly or editable.

**Comment by garykac** [comment]
Sorry for taking so long to get around to this. Let me know if there's anything else that would be useful to add.
