### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/uievents#144]
Would you like time at [TPAC](https://www.w3.org/2017/11/TPAC/) to update the WG on progress and/or bring issues up for discussion (with this or the two KeybardEvents specs)?

Please let me know by Friday 16th June. If yes, please also let me know how much time you think you'll need.

**Comment by LJWatson** [comment]
Thanks @garykac. Would 30 minutes give you enough time?

**Comment by garykac** [comment]
Plenty.
