### ISSUE TITLE
key-event-viewer does not work in Internet Explorer

### ISSUE THREAD

**Issue by rofrol** [w3c/uievents#188]
For Internet Explorer to work, change `for...of` to `forEach` and don't use default parameters like `setInputFocus(resetData=false)`.

**Comment by garykac** [comment]
The DomEventViewer now lives in https://github.com/garykac/dom-event-viewer (and can be used at https://domeventviewer.com/).

I don't think this is an issue that matters much anymore, but if you feel differently please open an issue in the dom-event-viewer repo.

Thanks!
