### ISSUE TITLE
D3E and corelation with DOM4(W3C)/DOM(WHATWAG) and DOM3 Core

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#19]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25485

##### Arkadiusz Michalski (Spirit) 2014-04-27 18:20:46 UTC
(In reply to Gary Kacmarcik)
>>Re: change ref to DOM3 Core. There has been no discussion of that, but if you
>>feel it should be changed, please open a bug for that so that we can discuss it.

and Anne comment (https://www.w3.org/Bugs/Public/show_bug.cgi?id=25359#c5)

any plans for changing ref to a more current spec? I see that D3E was started a long time ago (Tom Pixley, Netscape Communications Corporation (until Jul 2002)), and now still is not a recommendation. 

Maybe will be better it this document would base on the current DOM spec, which at the moment has good quality (and exist in two version: W3C and WHATWG). Many other specifications for a long time refers to the latest DOM (including HTML5).

This change could simplify the base D3E document, we don't need again defined basic interface, like Event, CustomEvent, EventTarget, EventListener (and probably DocumentEvent too). And some definition would be more consistent (like 'dispatch' and 'fire', which in new DOM are not synonymous). Current implementations (like browsers) when introducing new things using only the latest version of the DOM. For this implementations some concepts from D3E are still something news, but their definitions include the old DOM refs.

If not changing this version of the document is worth considering such a change on the next version D3E. It's just my little thoughts, but if someone wants to write something specific (with justification) please feel free.

##### Comment 1 Anne 2014-04-28 08:32:14 UTC
Yes, I feel this is long overdue now. We tried to get DOM Level 3 Events out quickly, that never happened. At this point the duplication is simply causing confusion.

##### Comment 2 Arkadiusz Michalski (Spirit) 2014-05-14 07:04:02 UTC
<garykac> If we remove the stuff covered in DOM4, then we remove Sections 3 and 4 (and a lot of glossary items)

In my opinion Section 3 is very helpful. DOM4 is economical in descriptions and has only two algorithms, but Section 3 explains everything in more detail (and other concepts, like synchronous/asynchronous, Activation triggers and behavior, etc...), has nice dispatched diagrams, just a good description for beginners (I am writing this from my own perspective and experience). Trying to understand all the basic things based only on the DOM4 (or HTML5) is difficult. Will be better just fit the text to the terminology DOM4, but not remove all.

Section 4 has nice diagram for interface inheritance which is also very useful, but descriptions for basic interfaces are unnecessary (you describe everything more details, but this info in most cases can be deduced directly from the DOM algorithms).

It's my small advice, both documents in some way complement each other (if we take into account the event processing).

##### Comment 3 Anne 2014-05-15 12:53:40 UTC
If you feel there's something missing in http://dom.spec.whatwg.org/ you should file a bug. This part of DOM Level 3 Events is obsoleted by that and will disappear in due course.

##### Comment 4 Arkadiusz Michalski (Spirit) 2014-05-19 21:18:17 UTC
Before make "big cleanup" please make last actual snapshot of current version for all, now last version (having its own link) derived from:

W3C Working Draft 06 September 2012
http://www.w3.org/TR/2012/WD-DOM-Level-3-Events-20120906/

This will make it easier to verify which possibly important things has been removed.

##### Comment 5 Travis Leithead [MSFT] 2014-05-28 00:07:44 UTC
We are putting together a proposed change for review. Should resolve the duplication between DOM4 and DOML3 Events.

##### Comment 6 Arthur Barstow 2015-03-21 15:12:01 UTC
Bulk move of all D3E bugs to the UI Events component.

**Comment by ArkadiuszMichalski** [comment]
https://github.com/whatwg/dom/issues/84#issuecomment-156139484 << this change make that "candidate event handlers/candidate event listeners" definition in UI Events also needs to be updated.

**Comment by garykac** [comment]
A lot of the duplicate definitions have been removed from the spec. And the recent change to bikeshed (for spec processing) automatically fixed a lot of these references to the most recent DOM specs.

I've also updated the glossary definition for candidate event handlers/listeners. Thanks for pointing that out.

**Comment by domenic** [comment]
This doesn't seem correct. It should be reopened until section 3 is removed.

**Comment by garykac** [comment]
I've (just) removed the majority of Section 3, but left the higher level overview in place to provide context for the rest of the spec. For the text that remains, the normative-sounding language (like MUST and SHOULD) has been removed and a link to DOM4 has been added to the top of the section as the definitive source.

**Comment by domenic** [comment]
Great! It would be useful if what remains could move to a MDN article instead of a spec.

**Comment by alsfyani** [comment]
<a class="_4s19 sec" href="#" role="button" aria-haspopup="true" data-sigil="touchable"></a>
