### ISSUE TITLE
Standardizing event.layerX and event.layerY

### ISSUE THREAD

**Issue by WebReflection** [w3c/uievents#193]
I am coming directly from [this WHATWG issue](https://github.com/whatwg/html/issues/3609), where @annevk rightly pointed me at this repository.

As mentioned in the original ticket, every Web developer that worked with canvas or any DOM element used as drawing surface, would like to use `layerX` and `layerY` as already implemented and expose in Chrome and WebKit browsers (probably Firefox too).

Even IE9, up to Edge, expose these properties but in a non de-facto standard way.

It would be awesome to have these two properties that represent same top-left X,Y coordinates system the canvas 2d context, as well as any CSS position, use.

Developers have been using ugly (and slow) workarounds for so many years we hope it's reasonable to ask standardizing these.

Thanks for consideration.

**Comment by annevk** [comment]
Sorry, I should have searched first. It seems this is #135.

**Comment by WebReflection** [comment]
1+ year ago last message ... I have a bad feeling about it ...
