### ISSUE TITLE
#event-type-input and #event-type-beforeinput appear to have gone missing

### ISSUE THREAD

**Issue by stuartpb** [w3c/uievents#2]
They're linked to all over the place on the page, but a section describing the `input` or `beforeinput` events doesn't appear anywhere on it (https://w3c.github.io/uievents/#event-type-input just links to the page without navigating to a section).

**Comment by travisleithead** [comment]
Yeah, we transitioned those events to the editing TF to spec. But obviously we still need to clean up that code... @w3c/editing

**Comment by johanneswilm** [comment]
Right, and the editing TF needs to figure out if we keep the name change to (before)Edit that we decided that the F2F meeting resolution says. @ojanvafai think we should change back to (before)Input, personally I do not care. The people from Apple had opinions on this, so it would be good to hear their opinion, @rniwa .

**Comment by annevk** [comment]
You cannot not just change the names of events that have already shipped.

**Comment by johanneswilm** [comment]
A) At the F2F we were not aware that the definition of those events had been moved to our spec.
B) beforeInput has not shipped.
C) We did some quick tests at the F2F, and the Input event did not seem to be triggered consistently in all browsers.

If we stick with the beforeEdit/Edit events names, I assume we keep the Input event for textarea and input fields.

**Comment by domenic** [comment]
`input` is widely used, and `beforeinput` should stay consistent with its counterpart.

**Comment by garykac** [comment]
`beforeinput` and `input` have been moved back into UIEvents, so those links should be working again.
