### ISSUE TITLE
Suppress default browser key handling for keyboard event tester

### ISSUE THREAD

**Issue by jamiewalch** [w3c/uievents#206]
The [keyboard event tester](http://w3c.github.io/uievents/tools/key-event-viewer.html) should have an option to call preventDefault() on keyboard events to prevent the browser from performing its default action. Without it, key combinations such as Shift+Ctrl+C are hard to examine because the browser swallows the keyup events for the modifiers.

**Comment by masayuki-nakano** [comment]
> The keyboard event tester should have an option to call preventDefault() on keyboard events to prevent the browser

It has.
1. Click "Show Options".
2. Check each checkboxes below "preventDefault".

**Comment by jamiewalch** [comment]
Thanks! I hadn't noticed those options.
