### ISSUE TITLE
Change click/auxclick/contextment/dblclick event types to PointerEvent?

### ISSUE THREAD

**Issue by NavidZ** [w3c/uievents#235]
@garykac @travisleithead @BoCupp-Microsoft @patrickhlauke  

We've seen some need to additional information for the meta events that are generated for different pointers. Attributes such as [pointerType](https://w3c.github.io/pointerevents/#dom-pointerevent-pointertype) seems to be useful for some web apps as mentioned in [this issue](https://github.com/w3c/pointerevents/issues/100) file against PointerEvent repository.
So we have two paths:

1. Either add all the attributes required back to the MouseEvent idl.
2. Just change these meta events (i.e. click, auxclick, contextmenu, and dblclick) type to the PointerEvent.

I wonder how ui events folks feel about the second solution. From PointerEvents perspective that seems to be a better long term solution but obviously we need to evaluate the compat impact of that.

**Comment by patrickhlauke** [comment]
noting that one of the compat issues may be the fact that in Pointer Events, the coordinates are fractional - likely the biggest potential problem, as scripts likely won't expect that
