### ISSUE TITLE
Propose the new navbeforefocus UIEvent

### ISSUE THREAD

**Issue by lgewst** [w3c/uievents#245]
CSS Spatial Navigation specification has been developed in CSS WG. One of the proposed APIs is NavigationEvent as a new interface with two event types(navbeforefocus, navnotarget).
https://drafts.csswg.org/css-nav-1/#events-navigationevent

Under reviews on how to implement them, I just wondered why focusin/focusout hadn't been defined as a cancellable. I found a related discussion on it at https://github.com/w3c/uievents/issues/88, but I couldn't see the reason at the thread.

Could someone explain the background or reason?
Any question or concern on the proposed navbeforefocus event is welcomed as well.
@dtapuska, @smaug----, @markelog

**Comment by lgewst** [comment]
need to change the account, sorry.

**Comment by smaug----** [comment]
focusin/focusout behave the way they behave just because how they get implemented at some point in one browser engine and then others had to follow that.
