### ISSUE TITLE
We don't have a definition for "contextmenu" event

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/uievents#279]
Apparently no spec defines `contextmenu` event!  The event is marked as a `MouseEvent` in a non-normative [section](https://html.spec.whatwg.org/multipage/indices.html#event-contextmenu) in the HTML spec, that's it.

As of today, it seems UI Event spec would be the place for it because the event is a MouseEvent in all major browsers.  Note, however, that we are planning to change it to a PointerEvent, see https://github.com/w3c/pointerevents/issues/100.

**Comment by garykac** [comment]
I have started documenting `contextmenu` in the algorithmic rewrite of uievents: https://w3c.github.io/uievents/event-algo.html

(also note the other hooks for PointerEvents in that document)

**Comment by mustaqahmed** [comment]
@garykac It seems to me that your algorithmic rewrite could be supplemented by a `contextmenu` event entry in the existing list of [Mouse Event Types](https://w3c.github.io/uievents/#events-mouse-types), which would provide non-algorithmic details like the event's attributes etc.  I am working on a PR now to create that entry, please let me know your thoughts.
