### ISSUE TITLE
Document the cancelability of wheel events

### ISSUE THREAD

**Issue by smfr** [w3c/uievents#282]
Touch events are documented to have a behavior where if all the listeners are `passive`, then the event has `cancelable=false`:
https://w3c.github.io/touch-events/#cancelability which links to https://dom.spec.whatwg.org/#observing-event-listeners

Blink seems to also apply this same logic to wheel events, but that is not described in https://w3c.github.io/uievents/. It probably should be.

**Comment by zcorpan** [comment]
Also `mousewheel`, if that event is supported.

**Comment by zcorpan** [comment]
Tests for this at https://github.com/web-platform-tests/wpt/pull/34464
