### ISSUE TITLE
Restore key/char/glyph styles

### ISSUE THREAD

**Issue by saschanaz** [w3c/uievents#312]
spec.css has styles for them but somehow were omitted during bikeshed migration.

**Comment by garykac** [comment]
These styles are applied in the `build.py` pre-processing step.

This was probably broken by the having the auto-publish call kikeshed directly without any pre-processing.

**Comment by saschanaz** [comment]
`build.py` does add classes but not the stylesheet itself 👀

**Comment by garykac** [comment]
!!  I know that was working in the past (with bikeshed), I wonder when it broke.
Anyway, thanks for catching this.

**Comment by garykac** [comment]
Apparently, these style files are no longer automatically included in the generated file. I have a workaround where I manually include the style files in the .BS file.
