### ISSUE TITLE
Keyboard Event Types: possible text missing. 

### ISSUE THREAD

**Issue by MelSumner** [w3c/uievents#324]
In section [5.6.4.1., keydown](https://www.w3.org/TR/uievents/#event-type-keydown), I think the last bullet point of the instructions for the default action is potentially missing a word. 

Text: 
> If the key is the Enter or   key and the current focus is on a state-changing element, the default action MUST be to dispatch a [click](https://www.w3.org/TR/uievents/#click) event, and a [DOMActivate](https://www.w3.org/TR/uievents/#domactivate) event if that event type is supported by the [user agent](https://www.w3.org/TR/uievents/#user-agent) (refer to [§ 3.5 Activation triggers and behavior](https://www.w3.org/TR/uievents/#event-flow-activation) for more details)

"If the key is the ENTER or .... key" 

Inspecting the code, it seems like something was meant to be here (or here previously):

```html
If the key is the <code class="keycap">Enter</code> or <code class="keycap">&nbsp;</code> key and the
current focus is on a state-changing element,
```

**Comment by garykac** [comment]
This is fixed by b5d4560a97341558acaa77548fdd498ddf897d26
Thanks!
