### ISSUE TITLE
Wheel event groups are not defined

### ISSUE THREAD

**Issue by dlrobertson** [w3c/uievents#338]
Both WebKit and Blink will group wheel events with a target, and I'm not sure if this is defined in [event-type-wheel](https://w3c.github.io/uievents/#event-type-wheel). Given the tests in https://github.com/web-platform-tests/wpt/pull/37445:

|Test| Blink | WebKit | Gecko |
|----|------|--------|--------|
|Wheel events are grouped and are not sent to a child element|:white_check_mark:|:white_check_mark:|:x:|
|Wheel events are not bound to a scroll frame|:white_check_mark:|:white_check_mark:|:white_check_mark:|
|Wheel event groups beyond the origin bound have the same target|:white_check_mark:|:x:|:x:|

Note: The failure in WebKit is due to an exception in the webdriver. When I manually run the steps, I get the expected behavior from the test.

Please let me know if any more information would be helpful. I'm working on fixing this in Gecko ([bug 1168182](https://bugzilla.mozilla.org/show_bug.cgi?id=1168182)), so any feedback would be very much welcomed (esp. feedback on the tests in https://github.com/web-platform-tests/wpt/pull/37445).

**Comment by zcorpan** [comment]
I think it shouldn't be non-normative, if browser engines agree on a behavior and it's sensible (in this case seems like better UX), it seems better to require that behavior in the spec.

**Comment by dlrobertson** [comment]
> I think it shouldn't be non-normative, if browser engines agree on a behavior and it's sensible (in this case seems like better UX), it seems better to require that behavior in the spec.

:+1: makes sense
