### ISSUE TITLE
Disable autocomplete on tools/key-event-viewer.html

### ISSUE THREAD

**Issue by rcyeh** [w3c/uievents#363]
When using https://w3c.github.io/uievents/tools/key-event-viewer.html, Chrome sometimes provides an autocomplete menu under the input element. If testing ArrowUp/ArrowDown events, that menu can interfere with the test. I would like to add an 'autocomplete="off"' attribute specification to that input field to prevent the autocomplete menu from popping up.

**Comment by garykac** [comment]
Migrated to the dom-event-viewer repo : https://github.com/garykac/dom-event-viewer/issues/9
