### ISSUE TITLE
KeyboardEvent.getKeyState()

### ISSUE THREAD

**Issue by polywock** [w3c/uievents#374]
## Problem 

Current web apps and games have trouble supporting non-modifier combination keys as it's difficult to determine which keys are currently pressed down. 

For modifier key combinations like Shift A, it's straightforward as you can check KeyboardEvent.shiftKey or KeyboardEvent.getModifierState. 

Listening to other types of combinations like A + S requires non-trivial amount of setup and testing (edge cases, extension interference, etc). 

## Proposal 

A method that tells you if a non-modifier key is currently pressed down. Similar to KeyboardEvent.getModifierState. 

```js
KeyboardEvent.getKeyState({key: "a"}) 

KeyboardEvent.getKeyState({code: "KeyA"})
```

**Comment by laughinghan** [comment]
Can you give examples of platform APIs (Windows, Java, etc) designed this way?

**Comment by laughinghan** [comment]
> For the web, this approach isn't viable as third party web extensions can interfere by preventing propagation.

The capturing phase happens before the bubbling phase, so couldn't you set a keyboard event handler at the top level (Window? Document?) in the capturing phase, so no stopPropagation could interfere with it?

**Comment by polywock** [comment]
Often that's fine, but sometimes when extensions want to support shortcut keys to activate various features of the extension, they will add a listener to the window and do stopImmediatePropogation(). That way they prevent the website from reacting to the event.

**Comment by laughinghan** [comment]
Sounds like an obscure case; I have difficulty imagining a well-behaved extension doing that. Can you give an example of a popular extension and shortcut where this happens, and why you'd want to know about the shortcut even though the extension handled it?

**Comment by laughinghan** [comment]
Gotcha, so it should be easy to list several examples then?

**Comment by polywock** [comment]
I'll just list mine. Four million users so not obscure at all. However, laughing right now because I'm pretty much pointing at myself for being part of the problem. 

https://microsoftedge.microsoft.com/addons/detail/global-speed/mjhlabbcmjflkpjknnicihkfnmbdfced

**Comment by laughinghan** [comment]
Very cool. What is the shortcut in question that the extension would like to suppress but you'd like the browser to still expose to the webpage?

**Comment by polywock** [comment]
Thanks! Nothing in particular. In fact, I'm no longer interested in this proposal. I should probably close this issue. Apologies for the trouble.
