### ISSUE TITLE
Reference to createEvent("FocusEvent")

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#41]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28119

##### Ms2ger 2015-03-01 11:55:58 UTC
"To create an instance of the FocusEvent interface, use the DocumentEvent.createEvent("FocusEvent") method call. "

The DOM spec does not actually support a FocusEvent argument here.

##### Comment 1 Ms2ger 2015-03-01 12:14:30 UTC
(Similar sentences exist for other event interfaces too.)

##### Comment 2 Arthur Barstow 2015-03-21 15:11:59 UTC
Bulk move of all D3E bugs to the UI Events component.

**Comment by travisleithead** [comment]
Already closed with checkin: https://github.com/w3c/uievents/commit/e5ba8aebeb6d1e2aa38cd6c637f59dce1c355981
