### ISSUE TITLE
CompositionEvent constructor arguments name are atypical

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#42]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28731

##### Philip Jägenstedt 2015-06-01 21:10:28 UTC
> Constructor(DOMString typeArg, optional CompositionEventInit compositionEventInitDict)

Event, UIEvent and many other events have a constructor on this form:

> Constructor(DOMString type, optional CompositionEventInit eventInitDict)

**Comment by garykac** [comment]
All the constructors now have consistent parameter naming.

**Comment by foolip** [comment]
My suggestion was actually to go with type/eventInitDict everywhere, as so many other specs do.

**Comment by garykac** [comment]
I renamed the one oddball constructor to make the names consistent within the spec, but I'm fine with either.

Renamed to type/eventInitDict in https://github.com/w3c/uievents/commit/1754524ea443411115a426cec552d4ff9192a28d

**Comment by foolip** [comment]
Thanks! The closer the IDL is in spec and implementation, the easier it is to spot the things that don't match!
