### ISSUE TITLE
CustomEvent.initCustomEvent() is in DOM

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#45]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28734

##### Philip Jägenstedt 2015-06-01 21:43:18 UTC
https://dom.spec.whatwg.org/#interface-customevent

In other words, it need not be defined again by UI Events.

**Comment by foolip** [comment]
CC @annevk

**Comment by travisleithead** [comment]
Fixed by: https://github.com/w3c/uievents/commit/b5c7942ee5b75ae7e213f12107a12ae0ce2e84fb

**Comment by foolip** [comment]
Thanks @travisleithead!
