### ISSUE TITLE
"Introduced in this specification" in IDL not helpful

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#46]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28735

##### Philip Jägenstedt 2015-06-01 21:51:27 UTC
https://w3c.github.io/uievents/#interface-MouseEvent

Here buttons is annotated with "Introduced in this specification"

This isn't helpful when one copies the IDL into the browser engine source, as I'm trying to do in Blink. It would be nicer to just list the attributes in the sensible order (buttons after button) and to put this note in the definition of the attribute, as for https://w3c.github.io/uievents/#widl-MouseEvent-getModifierState

##### Comment 1 Boris Zbarsky 2015-06-02 00:27:17 UTC
Even more to the point, unless this is the only definition of MouseEvent, this should probably be a partial interface....

##### Comment 2 Philip Jägenstedt 2015-06-02 07:40:24 UTC
This seems intended to be the main definition of MouseEvent.

**Comment by garykac** [comment]
These comments are no longer included in the IDL.

**Comment by foolip** [comment]
Thanks!
