### ISSUE TITLE
scroll should be a simple Event not a UIEvent

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#47]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28890

##### Rick Byers 2015-07-03 13:42:59 UTC
AFAIK all browsers implement it just as 'Event'.  Gary says the WG planned to change the spec (http://crbug.com/503280#c1).  This sounds like a good idea to me (makes my life easier: https://github.com/RByers/InputDevice/issues/5).

I could imagine there might be reasons to want to add to the scroll event in the future (eg. I've wanted velocity and maybe other properties on it), but we can cross that bridge if/when we come to it.

**Comment by travisleithead** [comment]
I think we talked about moving scroll out of the spec, since it appears to be much more precisely handled in https://drafts.csswg.org/cssom-view/#scrolling-events

**Comment by RByers** [comment]
Yeah CSSOM View seems to be the right place for details of scrolling.  Removing it from UI Events SGTM.

**Comment by garykac** [comment]
We need to talk to the CSS OM View spec editors to confirm that they're OK with taking this.

**Comment by travisleithead** [comment]
Note, I chatted with @zcorpan, who gave me the verbal handoff that we're free to drop this, and have this event continue to be spec'd in CSSOM View + HTML (for the task queue dependency).

**Comment by zcorpan** [comment]
Yep SGTM

**Comment by travisleithead** [comment]
Removed:
https://github.com/w3c/uievents/commit/adfb3c0d82137d6aa49fdb358b4d5038beba062d
