### ISSUE TITLE
"Legacy" appendices should be normative

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#50]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28967

##### Ms2ger 2015-07-20 07:46:23 UTC
Browsers need to implement them, so there's no reason to make them informative.

**Comment by travisleithead** [comment]
Move out of Appendix, re-title: Obsolete features (http://www.w3.org/TR/html5/obsolete.html#obsolete)

**Comment by garykac** [comment]
Fixed in https://github.com/w3c/DOM-Level-3-Events-key/commit/d4e48c719b2617d1159787865572cc0d82b27e2f
