### ISSUE TITLE
Should not recommend DocumentEvent.createEvent

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#51]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29068

##### Domenic Denicola 2015-08-19 21:36:53 UTC
"To create an instance of the KeyboardEvent interface, use the DocumentEvent.createEvent("KeyboardEvent") method call. "

You should recommend using new KeyboardEvent instead. DocumentEvent doesn't even exist.

This problem also occurs with CompositionEvent.

**Comment by travisleithead** [comment]
Finally got rid of that nasty text. Thanks!

See: https://github.com/w3c/uievents/commit/e5ba8aebeb6d1e2aa38cd6c637f59dce1c355981
