### ISSUE TITLE
Broken links make documentation useless

### ISSUE THREAD

**Issue by AFBarstow** [w3c/uievents#53]
This is a copy of "Broken links make documentation useless", filed as: https://github.com/w3c/editing/issues/90 and created by @IanKemp - 

[[
http://www.w3.org/TR/DOM-Level-3-Events/#event-types-list

Check the target of "input" in the table. Notice how it points to an anchor. Now click the link. Notice how you aren't taken to an anchor. Notice how the document you're taken to doesn't even mention the input event.

In the document you're taken to (https://w3c.github.io/editing/input-events.html), click the link at the top of the document below the "Latest published version:" text. Notice how this link takes you to an error 404 page.

This is not the first time I've encountered broken links on the W3C website, and I'm sure it won't be the last. For guys who are supposed to be custodians of the web, you're pretty terrible at making your own pages not break.
]]

@garykac @travisleithead - besides the above bug, the boilerplate info in http://www.w3.org/TR/2015/WD-uievents-20150428/ is not very out-of-date and as such, please publish a new WD soon.

**Comment by travisleithead** [comment]
While not perfect, I've fixed the InputEvent, beforeinput, and input event refs (updating as well to match latest changes in Edit Events spec.

See: dcb45bfa6c4185d474341078c8a515322f7ffc5b

Is there a short-name biblio ref for the Edit Events spec yet?

**Comment by travisleithead** [comment]
Forked my question off into issue #59. Closing this.

**Comment by garykac** [comment]
@johanneswilm 

At TPAC, I thought it was decided to undo the name change in the editing spec so that these are 'beforeinput' and 'input'.  Was there further discussion about this?

**Comment by garykac** [comment]
Related issue in Editing Spec: https://github.com/w3c/editing/issues/87

Name change reverted (beforeedit back to beforeinput) in https://github.com/w3c/editing/commit/a87f2b9c38891756f695067e614308af66abb8c2

**Comment by travisleithead** [comment]
We reverted the rename, should be no further problems. Otherwise, please let us know. Thanks!
