### ISSUE TITLE
Whethere KeyboardEvent.location depends on .code or .key?

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/uievents#62]
I realized that KeyboardEvent.location definition isn't clear to me.

If KeyboardEvent.location depends on .code value (I feel that this is intended), e.g., even if ControlLeft key is mapped to CapsLock, the value should be DOM_KEY_LOCATION_LEFT. And also if CapsLock key is mapped to left Control key, the value should be DOM_KEY_LOCATION_STANDARD.

Otherwise, i.e., KeyboardEvent.location depends on .key value (this is current Firefox for desktop's implementation), e.g., if ControlLeft key is mapped to CapsLock, the value should be DOM_KEY_LOCATION_STANDARD. And also if CapsLock key is mapped to left Control key, the value should be DOM_KEY_LOCATION_LEFT.

Although, physical key position can be retrieved with .code attribute, but left vs. right cannot be retrieved from .key attribute, so, web developers might expect the latter behavior.

**Comment by garykac** [comment]
I've viewed the location field as a way to disambiguate between 2 keys that share the same value.

Since 2 keys cannot (by definition) share the same |code|, this field only seems to make sense for |key| values. I would expect the remapping to change the |location| as part of the remapping.

It also seems very wrong to have the Control (or Shift, or Alt) key with a |location| of STANDARD. I imagine that would break sites that assume:

    if (location == left) {
        /* left */
    } else {
        /* right */
    }

**Comment by masayuki-nakano** [comment]
@garykac I agree with .location depending on .key.

> The location attribute contains an indication of the location of the key on the device.

I think that this should be:

The location attribute contains an indication of the _logical_ location of the key. The value does not indicate the physical key position on the device. For example, if 'ControlLeft' key is mapped to different key, the value may not be DOM_KEY_LOCATION_LEFT. Similarly, if 'CapsLock' key is mapped to left 'Control' key, the value should be DOM_KEY_LOCATION_LEFT.

Or something similar.

And I found serious issue in next sentence:

> In case a DOM implementation wishes to provide a new location value, a value different from the defined constant values MUST be used.

The spec shouldn't allow this. For example, if a browser uses 0x04, UI Events spec won't add new constant value as 0x04... Any new value should be suggested to us. If you think there should be private used area, you should define the range like 0xF0000000 - 0xFFFFFFFF.

**Comment by garykac** [comment]
Agree on both counts.

I'll update the description for location and remove the part where browsers can make up their own location.

**Comment by garykac** [comment]
I also looks like we need a table defining which keys permit location to be set to anything other than DOM_KEY_LOCATION_STANDARD so that the browsers don't allow Control to have |location| set to anything other than LEFT or RIGHT.

**Comment by garykac** [comment]
Fixed in https://github.com/w3c/uievents/commit/34137ee37935e800069b2d66bc3055de9b8a9811
