### ISSUE TITLE
"Modifier Keys" link in KeyboardEvent.getModifierState description is a 404

### ISSUE THREAD

**Issue by cvrebert** [w3c/uievents#63]
Quoting from https://w3c.github.io/uievents/#widl-KeyboardEvent-getModifierState :
> Valid modifier keys are defined in the [Modifier Keys](https://w3c.github.io/uievents/DOM3Events-key.html#keys-modifier) table

The link (to https://w3c.github.io/uievents/DOM3Events-key.html#keys-modifier ) leads to a 404 error page.

**Comment by garykac** [comment]
This is fixed in the latest ED. Thank you for reporting this.
