### ISSUE TITLE
Request example for DomKey when Ctrl and CapsLock are both down

### ISSUE THREAD

**Issue by choniong** [w3c/uievents#70]
According to https://w3c.github.io/uievents/#keys-guidelines Rule 3 `Ctrl+CapsLock+c` should ignore `CapsLock` and produce `'c'`, but FF is producing `'C'`.

Requesting an example to clarify.

**Comment by masayuki-nakano** [comment]
I think that `CapsLock` and `NumLock` should be honored because `CapsLock` (and `ShiftLock` in some keyboard layouts) typically doesn't cause making printable keys not input any text and also ignoring `NumLock` key state doesn't make sense (E.g., `Ctrl + NumPad1` should cause '1').

**Comment by garykac** [comment]
The spec currently says
> ...the key value should be the printable key value that would have been produced if the key had been typed with the default keyboard layout with no modifier keys except for 'Shift' and 'AltGr' applied.

I think it makes sense to include `CapsLock` as well.

The problem with `NumLock` is that `Numpad5` doesn't have a `key` value defined without the `NumLock` modifier.  However, we could define one to avoid that problem.

**Comment by garykac** [comment]
This issue was moved to w3c/uievents-key#39
