### ISSUE TITLE
Request 'inputType' field in Keyboard Event Viewer

### ISSUE THREAD

**Issue by choniong** [w3c/uievents#71]
According to http://w3c.github.io/editing/input-events.html#h-interface-inputevent `InputEvent` has field `inputType`, it will help if we can have the field displayed in the Keyboard Event Viewer.

**Comment by garykac** [comment]
Fixed in ee9d1877d19695f80fcd42e33439b896beb51582

**Comment by choniong** [comment]
Just to confirm should it be `inputType` or `eventType`?
[Editing Spec](http://w3c.github.io/editing/input-events.html#widl-InputEvent-inputType) says `inputType` but [ee9d187](https://github.com/w3c/uievents/commit/ee9d1877d19695f80fcd42e33439b896beb51582) uses `eventinfo["eventType"] = e.eventType;`

Or it's a bug for Editing Spec?

**Comment by garykac** [comment]
It should be 'inputType', my fingers just typed eventType by habit (since I use eventType elsewhere).

Thanks for catching that. I've updated a fix https://github.com/w3c/uievents/commit/a349546d0356973cded8906163ba60cfc5dfe7ba

**Comment by choniong** [comment]
It's complaining about 

```
key-event-viewer.js:331 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

addTableCell	@	key-event-viewer.js:331
addEvent	@	key-event-viewer.js:204
```

Perhaps `addTableCellText`?

**Comment by garykac** [comment]
Yes. Do we have any browsers that produce this field yet?  I tried FF and Chrome Canary and they don't populate it yet, so all I see are 'undefined' values.

In any case, changed to addTableCellText in https://github.com/w3c/uievents/commit/7f2f1b6f7cfa1305e428f97f1090e2f3fa4ea3b6
