### ISSUE TITLE
The `resize` event isn't a UIEvent

### ISSUE THREAD

**Issue by cvrebert** [w3c/uievents#76]
In Safari, Firefox, and Chrome, [`resize`](https://w3c.github.io/uievents/#event-type-resize) events are instances of `Event`, not of `UIEvent` as this spec currently claims. Only MS Edge currently uses `UIEvent` for `resize`.

Also, CSSOM View specifies `resize` as a plain `Event`. Per https://drafts.csswg.org/cssom-view/#resizing-viewports :
> [...] *fire an event named `resize`* at the Window object associated with doc

And per https://dom.spec.whatwg.org/#concept-event-fire
> To "fire an event named e" means that a new event using the `Event` interface, [...]

**Comment by garykac** [comment]
It seems a bit odd to keep it in UIEvents if it is an instance of `Event` rather than `UIEvent`.

But I can't think of another place for it to live. If there are no objections or suggestions for an alternate location, I'll add a section for `Event`-based UIEvents.

**Comment by cvrebert** [comment]
Dunno. I suppose it could be moved to CSSOM View [like the `scroll` event was](https://github.com/w3c/uievents/issues/47).

**Comment by garykac** [comment]
@zcorpan @travisleithead Does moving `resize` into CSSOM (like we did with `scroll`) sound reasonable?

**Comment by zcorpan** [comment]
Yes, it's defined there already and integrates with HTML's event loop, so it should be well-defined *when* exactly it should be fired, and cover the same ground as the first two paragraphs in UIEvents.

The third paragraph:

> The Window object SHOULD always be resizable. A host language MAY define certain elements to be resizable, and under what conditions (e.g., specific elements like &lt;iframe>, or elements with particular characteristics like width and height). However, this specification does not define the behavior for elements.

...doesn't really make any sense to me.

**Comment by cvrebert** [comment]
> Only MS Edge currently uses `UIEvent` for `resize`.

Filed https://connect.microsoft.com/IE/Feedback/Details/2455552

**Comment by plehegar** [comment]
This might help here: The resize event on touchscreen:
 http://www.quirksmode.org/blog/archives/2016/03/the_resize_even_2.html
http://www.quirksmode.org/dom/events/resize_mobile.html

**Comment by travisleithead** [comment]
Edge had a pre-existing bug to switch `resize` to `Event` from `UIEvent`, but thanks for the extra feedback :-)

+1 for removing resize from UIEvents spec.

**Comment by garykac** [comment]
@zcorpan wrote:
> The third paragraph:
> 
> > The Window object SHOULD always be resizable. A host language MAY define certain elements to be resizable, and under what conditions (e.g., specific elements like &lt;iframe&gt;, or elements with particular characteristics like width and height). However, this specification does not define the behavior for elements.
> 
> doesn't really make any sense to me.

I read that as: "Windows are resizeable. Other things might be resizeable too, but we don't bother specifying them here."

That text looks like a catch-all to cover the case where some user agents are sending `resize` on non-Window objects and we didn't want the spec to disallow it. I don't think it adds much value unless we define what other objects can send `resize`, so I think it's safe to delete.
