### ISSUE TITLE
Support Event.composed

### ISSUE THREAD

**Issue by hayatoito** [w3c/uievents#89]
The context: https://github.com/w3c/webcomponents/issues/513

Could someone give me advice how we should update UIEvents specification so it considers Event.composed?

Is a Pull Request a recommended way?

**Comment by RByers** [comment]
Yes PRs are typically how updates are done.  /cc @garykac 
I suggest we focus first on the UIEvents PR before deciding what exact pattern to follow for the subclass specs (w3c/pointerevents#91 and w3c/touch-events#66).

**Comment by hayatoito** [comment]
Thank you. I have sent a PR: https://github.com/w3c/uievents/pull/91.

**Comment by hayatoito** [comment]
All pull requests have been merged.

- https://github.com/w3c/uievents/pull/91 
- https://github.com/w3c/touch-events/pull/67
- https://github.com/w3c/pointerevents/pull/92

Let me close this issue.
